### ISSUE TITLE
Error Python 3.10

### ISSUE THREAD

**Issue by Neurowerk** [kujosHeist/tle2czml#9]
Hi, i used tle2czml in Python 3.10 and Python 3.6. In Python 3.6 tle2czml works corrects, but when i use tle3czml in Python 3.10, i have next:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\tletoczml\tleczml.py", line 1, in <module>
    import tle2czml
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\tle2czml\__init__.py", line 3, in <module>
    from .czml import (CZML, Billboard, CZMLPacket, Description, Label, Path,
  File "C:\Users\Use\AppData\Roaming\Python\Python310\site-packages\tle2czml\czml.py", line 38, in <module>
    from pygeoif.geometry import as_shape as asShape
ImportError: cannot import name 'as_shape' from 'pygeoif.geometry' (C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pygeoif\geometry.py)

How to fix this error?

**Comment by lpfandr** [comment]
https://blog.csdn.net/qq_15028721/article/details/130593533

**Comment by RPZ97** [comment]
try:
    from pygeoif.geometry import as_shape as asShape
except:
    from pygeoif.factories import shape as asShape

**Comment by yeongu-dev** [comment]
`pip install pygeoif==0.7 -i https://pypi.tuna.tsinghua.edu.cn/simple`
